services:
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672'
  mariadb:
    image: 'mariadb:latest'
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=twf
    command: --init-file /data/application/initdb.sql
    volumes:
      - ./initdb.sql:/data/application/initdb.sql
    ports:
      - "3306:3306"